name: "framework tests"
on:
  workflow_dispatch:
  schedule:
    # Daily, 3:00pm
    - cron: '00 15 * * *'

jobs:
  cleaner:
    runs-on: self-hosted
    steps:
      - name: Runner workspace path
        run: |
          echo "Cleaning up previous run"
          sudo rm -rf /home/runner/work/k8devel/
          sudo rm -rf /home/runner/_work/k8devel/
  framework-tests:
    needs: [cleaner]
    runs-on: self-hosted
    env:
      GOPATH: /home/runner/work/k8devel/go
      GO111MODULE: auto
    steps:
      - uses: actions/checkout@v2
        with:
           path: main

        # Setup Go
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.x'
      - uses: actions/checkout@master
        with:
          repository: thekubeworld/k8s-local-dev
          path: k8s-local-dev
      - run: |
          sudo dnf install patch -y
          pushd ./k8s-local-dev
            ./k8s-local-dev kindnetd
          popd
          pushd ./main
            mkdir -p downloads
            # download the k8devel lib
            mkdir -p $GOPATH/src/github.com/thekubeworld
            pushd $GOPATH/src/github.com/thekubeworld
              git clone http://github.com/thekubeworld/k8devel/
            popd
            examples=(apply delete base64 pod metallb configmap/listAll configmap/createConfig deployment endpoint execute_command_inside_container namespace podsecuritypolicy service/clusterip/ secret serviceaccount util)
            echo $pwd
            echo "dir 0"
            for name in "${examples[@]}"; do
                pushd examples/$name/
                    echo "dir..."
                    $pwd
                    go run *.go
                popd
            done
          popd
  cleanerpostrun:
    needs: [framework-tests]
    runs-on: self-hosted
    steps:
      - name: Runner workspace path
        run: |
          echo "Cleaning up previous run"
          rm -rf /home/runner/work/k8devel/
          rm -rf /home/runner/_work/k8devel/
