name: "framework tests"
on:
  workflow_dispatch:
  schedule:
    # Daily, 3:00pm
    - cron: '00 15 * * *'

jobs:
  cleaner:
    runs-on: self-hosted
    steps:
      - id: clean
        #- name: Cleaning up the $GITHUB_WORKSPACE as root from a Docker image
        # Volume auto mounted by gh actions pointing to the current working-directory
        run: 
          find /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}/. -name . -o -prune -exec rm -rf -- {} + || true
          sudo chown -R $USER:$USER /home/runner/_work/k8devel
          #sudo rm -rf /home/runner/work/k8devel/
          #sudo rm -rf /home/runner/_work/k8devel/
  framework-tests:
    needs: [cleaner]
    runs-on: self-hosted
    env:
      GOPATH: /home/runner/work/k8devel/go
      GO111MODULE: auto
    steps:
      - uses: actions/checkout@v2
        with:
           path: main

        # Setup Go
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.x'
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
          repository: thekubeworld/k8s-local-dev
          path: k8s-local-dev
      - run: |
          kind version
          kind get clusters
          sudo apt update -y
          sudo apt install patch -y
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
          pushd ./k8s-local-dev
            ./k8s-local-dev kindnetd
          popd
          pushd ./main
            mkdir -p downloads
            # download the k8devel lib
            mkdir -p $GOPATH/src/github.com/thekubeworld
            pushd $GOPATH/src/github.com/thekubeworld
              git clone http://github.com/thekubeworld/k8devel/
            popd
            examples=(apply delete base64 metallb configmap/listAll configmap/createConfig deployment endpoint namespace podsecuritypolicy service/clusterip/ secret serviceaccount util)
            for name in "${examples[@]}"; do
                pushd examples/$name/
                    go run *.go
                popd
            done
          popd
