name: "framework tests"
on:
  workflow_dispatch:
  schedule:
    # Daily, 3:00pm
    - cron: '00 15 * * *'

jobs:
  framework-tests:
    runs-on: [ ubuntu-18.04 ]
    env:
      GOPATH: /home/runner/work/k8devel/go
      GO111MODULE: auto
    steps:
      - uses: actions/checkout@v2
        with:
           path: main

        # Setup Go
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.x'
      - uses: actions/checkout@master
        with:
          repository: thekubeworld/k8s-local-dev
          path: k8s-local-dev
      - run: |
          pushd ./k8s-local-dev
            ./k8s-local-dev kindnetd
          popd
          pushd ./main
            mkdir -p downloads
            # download the k8devel lib
            mkdir -p $GOPATH/src/github.com/thekubeworld
            pushd $GOPATH/src/github.com/thekubeworld
            git clone http://github.com/thekubeworld/k8devel/
            popd

            # Execute examples
            examples=(apply delete base64 pod metallb configmap/listAll configmap/createConfig deployment endpoint execute_command_inside_container namespace podsecuritypolicy service/clusterip/ secret serviceaccount util)
            for name in "${examples[@]}"; do
                pushd examples/$name/
                    go run *.go
                popd
            done
          popd
