name: Mirror K8sbykeshed
on:
  workflow_dispatch:
  schedule:
    # Daily, 3:00pm
    - cron: '00 15 * * *'

jobs:
  to_K8sbykeshed:
    runs-on: ubuntu-latest
    steps:
      - name: sycnmain
        uses: wei/git-sync@v3
        with:
          source_repo: "https://${{GITHUB_TOKEN}}@github.com:thekubeworld/k8devel.git"
          source_branch: "main"
          destination_repo: "git@github.com:K8sbykeshed/k8devel.git"
          destination_branch: "main"
      - name: synctags
        uses: wei/git-sync@v3
        with:
          source_repo: "thekubeworld/k8devel"
          source_branch: "refs/tags/*"
          destination_repo: "K8sbykeshed/k8devel"
          destination_branch: "refs/tags/*"
          source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
          destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`

